// Load amplify_outputs.json (generated by npx ampx sandbox)
// @ts-ignore - JSON import
import outputs from '../../amplify_outputs.json';

// Configure Amplify v6 with Gen 2 outputs
// In Amplify v6, configuration is done via the outputs object
// The configure function is available from aws-amplify package
// @ts-ignore - aws-amplify types may not be fully available during build
import { Amplify } from 'aws-amplify';

// This must run synchronously at module load time
const hasValidConfig = 
  (outputs?.auth?.user_pool_id && outputs.auth.user_pool_id !== 'placeholder') ||
  (outputs?.data?.url && outputs.data.url !== 'placeholder');

if (hasValidConfig) {
  // Amplify v6 handles amplify_outputs.json directly
  // Storage is automatically configured for browser environments
  Amplify.configure(outputs);
  console.log('Amplify configured successfully');
} else {
  console.warn('amplify_outputs.json contains placeholder values. Run "npx ampx sandbox" to generate real configuration.');
}

export default Amplify;
